spring:
  config:
    import: nacos:im-socket.yml?refresh=true
  cloud:
    nacos:
      config:
        context-path: /nacos
        server-addr: 115.126.42.129:8848
#        server-addr: 127.0.0.1:8848

